name: Build
on: workflow_dispatch
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL:  ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  
  APP_NAME: template name
  
jobs:
  buildAndroidAPK:
    name: Compile APK
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - uses: actions/cache@v2
      with:
        path: Library
        key: Library-${{ matrix.targetPlatform }}
        restore-keys: Library-
    - uses: game-ci/unity-builder@v2.1.2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        buildName: ${{ env.APP_NAME }}
        targetPlatform: Android
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }}
        path: build/Android
        
    - uses: BetaHuhn/do-spaces-action@v2
      with:
        out_dir: "./apk"
        access_key: "DO00HC4QQ7CERVVGHCJF"
        secret_key: "dop_v1_79d3ec91b5cc466c211ba971e25873c87b68dd5742c0e0aeaf47470e4bae60cc"
        space_name: "myeasyapp"
        space_region: "ams3"
        source: '${{ github.workspace }}/build/Android/${{ env.APP_NAME }}.apk'