name: Build
on: workflow_dispatch
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  APP_NAME: Uses

jobs:

  EncodeKeystoreToBase64:
    name: Encode Keystore
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Encoding to base64 string
        id: encoding
        run: base64 ${{ github.workspace }}/user.keystore
        
  buildAndroidAPK:
    name: Compile APK
    runs-on: ubuntu-latest
    needs: EncodeKeystoreToBase64
    strategy:
      fail-fast: false
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - uses: actions/cache@v2
      with:
        path: Library
        key: Library-${{ matrix.targetPlatform }}
        restore-keys: Library-
        
    - uses: game-ci/unity-builder@v2.1.2
      with:
        buildName: ${{ env.APP_NAME }}
        androidAppBundle: false
        androidKeystoreName: user.keystore
        androidKeystoreBase64: ${{needs.EncodeKeystoreToBase64.outputs.encoding}}
        androidKeystorePass: ${{ secrets.androidKeystorePass }}
        androidKeyaliasName: ${{ secrets.androidKeyaliasName }}
        androidKeyaliasPass: ${{ secrets.androidKeystorePass }}
        targetPlatform: Android
        
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }}
        path: build/Android
        
    - uses: BetaHuhn/do-spaces-action@v2
      with:
        out_dir: ${{ secrets.SOURCE_DIR}}
        access_key: ${{ secrets.ACCESS_KEY}}
        secret_key: ${{ secrets.SECRET_KEY }}
        space_name: ${{ secrets.SPACE_NAME }}
        space_region: ${{ secrets.SPACE_REGION }}
        source: build/Android/${{ env.APP_NAME }}.apk
        
  buildAndroidAAB:
    name: Compile AAB
    runs-on: ubuntu-latest
    needs: EncodeKeystoreToBase64
    strategy:
      fail-fast: false
      
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v2.1.2
        with:
          buildName: ${{ env.APP_NAME }}
          androidAppBundle: true
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{needs.EncodeKeystoreToBase64.outputs.encoding}}
          androidKeystorePass: ${{ secrets.androidKeystorePass }}
          androidKeyaliasName: ${{ secrets.androidKeyaliasName }}
          androidKeyaliasPass: ${{ secrets.androidKeystorePass }}
          targetPlatform: Android
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}
          path: build/Android
          
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          out_dir: ${{ secrets.SOURCE_DIR}}
          access_key: ${{ secrets.ACCESS_KEY}}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: build/Android/${{ env.APP_NAME }}.aab
          
  Endpoint:
    name: endpoint
    runs-on: ubuntu-latest
    needs: [buildAndroidAPK,buildAndroidAAB]
    
    steps:
    
      - name: Log
        run: echo "endpoint"
